name: Deploy to EC2

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: deploy to ec2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      env:
        PRIVATE_KEY: ${{ secrets.key}}
        HOST_NAME: ${{ secrets.url}}
        USER_NAME: ubuntu
      run:
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key &&
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@{HOST_NAME} &&
        ls &&
        git pull &&
        pyrhon3 app.py